---
- hosts: localhost
  collections:
  - community.general
  tasks:
  - name: gather facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: Return all entries within the 'groups' organizational unit.
    ldap_search:
      dn: "ou=groups,dc=example,dc=com"
    register: ldap_groups
